[package]
name = "example"
version = "0.1.0"
edition = "2024"
publish = false

[features]
default = []
minify = ["leptos_ssg/minify"]

[dependencies]
leptos_ssg = { path = ".." }
leptos = { workspace = true }
