name: Example site

on:
  push:
    branches: ["master"]
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build and deploy example site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # build website
      - uses: dtolnay/rust-toolchain@stable
      - run: cd example && cargo run --release

      # github actions specific: move 404 page with other files
      - run: mv example/target/example-site/extra/404.html example/target/example-site/www/404.html

      # generate css with tailwind
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: cd example && nix-shell -p tailwindcss_4 --run 'tailwindcss --cwd ../src --minify' > target/example-site/www/style.css

      # list files to deploy
      - run: tree example/target/example-site

      # upload to github pages
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./example/target/example-site/www"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
