name: Opengraph
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: cachix/install-nix-action@v31
    - name: Get Nixpkgs path
      run: |
        nixpkgs_path=$(nix eval --raw -f npins/default.nix nixpkgs)
        echo "NIX_PATH=nixpkgs=$nixpkgs_path" >> "$GITHUB_ENV"
    - run: nix-shell --arg headless true --run "cd example && cp-tailwind-opengraph /tmp/opengraph.css"
    - run: nix-shell --arg headless true --run "cd example && runWithGeckodriver cargo run --features opengraph /tmp/opengraph.css"
    - run: nix-shell --arg headless true --run "cd example && cp-tailwind-leptos_ssg target/example-site/style.css"
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - run: npm ci
    - run: npx playwright install --with-deps
    - run: cd opengraph && npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    - name: Get supervisor logs
      if: ${{ failure() }}
      run: |
        cat .supervisor/log/supervisord.log
        cat .supervisor/log/geckodriver-stdout*
        cat .supervisor/log/geckodriver-stderr*
