name: Playwright Tests for example site
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # build website
    - uses: dtolnay/rust-toolchain@stable
    - name: Build example site
      run: cd example && cargo run
    # generate css with tailwind
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: cd example && nix-shell -p tailwindcss_4 --run 'tailwindcss --cwd ../src ' > target/example-site/style.css
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
